### PR TITLE
fix: Incorrect window title from `setcrs`

### LINKED ISSUE #75: `setcrs` command missing space
There is a missing space after running the set course command.

## Example

Before: `Course: CS1234`

Run this comand:
```
setcrs cs1234
```

After: `Course:CS1234`
* A space is missing

### LINKED ISSUE #76: Window title could contain `TAPro`
Currently, the title is like this: `Course: CS1234`.

Suggestion: `TAPro | Course: CS1234`
* The title could contain the name of our product.

### PR DESCRIPTION
**Pull request by tituschewxj**
Let's
* Fix missing space in title after `setcrs`
* Add APP_NAME into title

New title is now in this format: `TAPro | Course: XX1234Y`

Resolves #75, resolves #76

### CODE REVIEW

**Review by ForAeons — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -93,12 +91,19 @@ public Stage getPrimaryStage() {
         return primaryStage;
     }
 
+    /**
+     * Generates a title containing {@link MainApp#APP_NAME} from the {@code courseName}.
+     */
+    private String generateWindowTitle(String courseName) {
+        return APP_NAME + " | Course: " + courseName;
```
Comment (belligerentbeagle) [inline src/main/java/seedu/address/ui/MainWindow.java:98]: Thanks for thinking about this! Agree that we should have our app name included!

**Review by belligerentbeagle — APPROVED** [review]
LGTM!
