### PR TITLE
Use up-down arrows to navigate previous commands

### LINKED ISSUE #88: Use up down arrow to navigate previous commands so that I can rerun commands faster.

### LINKED ISSUE #96: Missing space in: NUSNET wrong format message
Screenshot 2024-03-27 191441

### PR DESCRIPTION
**Pull request by belligerentbeagle**
Resolves #88

Resolves #96

### CODE REVIEW

**Review by Anant1902 — APPROVED** [review]
LGTM! Great job with this feature Ethan.

File: src/main/java/seedu/address/model/person/NusNet.java
Comment (saiutkarsh33) [inline src/main/java/seedu/address/model/person/NusNet.java:1]: Is there a reason why " is on another line here?

File: src/test/java/seedu/address/ui/CommandHistoryTest.java
Comment (saiutkarsh33) [inline src/test/java/seedu/address/ui/CommandHistoryTest.java:1]: Very rigorous unit testing here. bravo!

File: src/main/java/seedu/address/ui/CommandHistory.java
Comment (saiutkarsh33) [inline src/main/java/seedu/address/ui/CommandHistory.java:1]: Javadocs could be more varied/ thorough

**Review by saiutkarsh33 — CHANGES_REQUESTED** [review]
Overall, Looks good. Just some minot nitpicks but overall, LGTM

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 1]
```diff
@@ -33,7 +33,7 @@ public CommandBox(CommandExecutor commandExecutor, AutoCompleteExecutor autoComp
         this.autoCompleteExecutor = autoCompleteExecutor;
         // calls #setStyleToDefault() whenever there is a change to the text of the command box.
         commandTextField.textProperty().addListener((unused1, unused2, unused3) -> setStyleToDefault());
-
+        commandTextField.setOnKeyPressed(this::handleArrowKeyPressed);
```
Comment (ForAeons) [inline src/main/java/seedu/address/ui/CommandBox.java:36]: Could you refactor this into `handleKeyPressEvent` to apply SLAP?

```
    private void handleKeyPressEvent(KeyEvent e) {
        switch (e.getCode()) {
        case TAB:
            handleTabKeyPressEvent(e);
            break;
        case UP:
            // fall through
        case DOWN:
            handleArrowKeyPressed(e);
        default:
            break;
        }
    }
```

**Review by ForAeons — CHANGES_REQUESTED** [review]
Amazing quality of life feature, just a few nits

File: src/main/java/seedu/address/model/person/NusNet.java [hunk 2]
```diff
@@ -9,7 +9,7 @@
  */
 public class NusNet {
 
-    public static final String MESSAGE_CONSTRAINTS = "NUSNET should be of the format E"
+    public static final String MESSAGE_CONSTRAINTS = "NUSNET should be of the format E "
         + "followed by 7 digits";
```
Comment (tituschewxj) [inline src/main/java/seedu/address/model/person/NusNet.java:13]: This resolves #96

File: src/main/java/seedu/address/model/person/NusNet.java
Comment (belligerentbeagle) [reply src/main/java/seedu/address/model/person/NusNet.java:1]: I'm not sure either, I believe it was previously @ForAeons 's code
@ForAeons any reason? else I'll just put it to single line

Comment (belligerentbeagle) [reply src/main/java/seedu/address/model/person/NusNet.java:1]: Oh and thanks for helping me review @saiutkarsh33

File: src/main/java/seedu/address/ui/CommandBox.java (hunk 1 above)
Comment (belligerentbeagle) [reply src/main/java/seedu/address/ui/CommandBox.java:36]: Sure!

File: src/test/java/seedu/address/ui/CommandHistoryTest.java
Comment (belligerentbeagle) [reply src/test/java/seedu/address/ui/CommandHistoryTest.java:1]: Thanks man!

File: src/main/java/seedu/address/ui/CommandHistory.java
Comment (belligerentbeagle) [reply src/main/java/seedu/address/ui/CommandHistory.java:1]: Done

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 3]
```diff
@@ -55,6 +54,19 @@ private void handleCommandEntered() {
         }
     }
 
+    /**
+     * Handles the Up and Down arrow key pressed event.
+     */
+    @FXML
+    private void handleArrowKeyPressed(KeyEvent event) {
+        if (event.getCode().toString().equals("UP") || event.getCode().toString().equals("DOWN")) {
```
Comment (ForAeons) [inline src/main/java/seedu/address/ui/CommandBox.java:62]: Just one final nit: since the HandleKeyPress function already checks for the key pressed, theres actually no need to check for key again here

**Review by ForAeons — CHANGES_REQUESTED** [review]
Just one final nit, we can merge this afterwards

File: src/main/java/seedu/address/ui/CommandBox.java (hunk 3 above)
Comment (belligerentbeagle) [reply src/main/java/seedu/address/ui/CommandBox.java:62]: okay!

Comment (belligerentbeagle) [reply src/main/java/seedu/address/ui/CommandBox.java]: Side qn, is this considered like code quality improvement or

Comment (ForAeons) [reply src/main/java/seedu/address/ui/CommandBox.java]: I would consider it code quality/style since logic wise this makes no difference

**Review by ForAeons — APPROVED** [review]
Fantastic work!
